[font]
size = 17

[window]
startup_mode = "Maximized"
decorations = "None"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 15
y = 15

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[colors.primary]
background = "#000000"

